# Dieser Service macht die Anwendung, die in den Pods läuft, über das Netzwerk zugänglich.
# Um diesen Service mit kubectl auszuführen, verwenden Sie den Befehl:
# kubectl apply -f service.yaml

apiVersion: v1  # Die API-Version, die für den Service verwendet wird
kind: Service  # Der Typ der Ressource, in diesem Fall ein Service
metadata:
  name: blog-service  # Der Name des Services
spec:
  selector:
    app: blog  # Label-Selector, um die Pods auszuwählen, die von diesem Service bedient werden
  ports:
    - protocol: TCP  # Das verwendete Protokoll, in diesem Fall TCP
      port: 3000  # Der Port, der vom Service exponiert wird (externer Port)
      targetPort: 3000  # Der Zielport im Container, auf den der externe Port weitergeleitet wird
      nodePort: 30080  # Der NodePort, der auf dem Host geöffnet wird, um den Service zugänglich zu machen
  type: NodePort  # Der Typ des Services, in diesem Fall NodePort, um den Service über einen bestimmten Port auf dem Host zugänglich zu machen